
INSERT INTO USER_LIST (USERNAME) VALUES ('John');
INSERT INTO USER_LIST (USERNAME) VALUES ('John1');
INSERT INTO USER_LIST (USERNAME) VALUES ('John2');
INSERT INTO USER_LIST (USERNAME) VALUES ('John3');
INSERT INTO USER_LIST (USERNAME) VALUES ('John4');
INSERT INTO USER_LIST (USERNAME) VALUES ('John5');
INSERT INTO USER_LIST (USERNAME) VALUES ('John6');
INSERT INTO USER_LIST (USERNAME) VALUES ('John7');
INSERT INTO USER_LIST (USERNAME) VALUES ('John8');
INSERT INTO USER_LIST (USERNAME) VALUES ('John9');
INSERT INTO USER_LIST (USERNAME) VALUES ('John10');
INSERT INTO USER_LIST (USERNAME) VALUES ('John11');
INSERT INTO USER_LIST (USERNAME) VALUES ('John12');
INSERT INTO USER_LIST (USERNAME) VALUES ('John13');
INSERT INTO USER_LIST (USERNAME) VALUES ('John14');
INSERT INTO USER_LIST (USERNAME) VALUES ('John15');
INSERT INTO USER_LIST (USERNAME) VALUES ('John16');
INSERT INTO USER_LIST (USERNAME) VALUES ('John17');

INSERT INTO RESTRICTED_WORDS (WORD) VALUES ('cannabis');
INSERT INTO RESTRICTED_WORDS (WORD) VALUES ('abuse');
INSERT INTO RESTRICTED_WORDS (WORD) VALUES ('crack');
INSERT INTO RESTRICTED_WORDS (WORD) VALUES ('damn');
INSERT INTO RESTRICTED_WORDS (WORD) VALUES ('drunk');
INSERT INTO RESTRICTED_WORDS (WORD) VALUES ('grass');
