
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn1');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn2');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn3');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn4');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn5');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn6');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn7');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn8');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn9');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn10');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn11');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn12');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn13');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn14');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn15');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn16');
INSERT INTO USER_LIST (USERNAME) VALUES ('MrJohn17');

INSERT INTO RESTRICTED_WORDS (WORD) VALUES ('cannabis');
INSERT INTO RESTRICTED_WORDS (WORD) VALUES ('abuse');
INSERT INTO RESTRICTED_WORDS (WORD) VALUES ('crack');
INSERT INTO RESTRICTED_WORDS (WORD) VALUES ('damn');
INSERT INTO RESTRICTED_WORDS (WORD) VALUES ('drunk');
INSERT INTO RESTRICTED_WORDS (WORD) VALUES ('grass');
